USE SCHOOL;

SELECT * FROM titanic WHERE AGE BETWEEN 20 AND 30 ORDER BY AGE DESC;

DELIMITER $$
CREATE PROCEDURE AG()
BEGIN 
SELECT *FROM TITANIC WHERE AGE = 54 ;
END $$
DELIMITER ;

DELIMITER //
CREATE PROCEDURE RT(IN WER INT)
BEGIN 
   SELECT * FROM TITANIC WHERE AGE = WER ;
END //
   DELIMITER;

DELIMITER //
CREATE PROCEDURE RT3(IN WER INT , SD VARCHAR(26))
BEGIN 
   SELECT * FROM TITANIC WHERE AGE = WER AND SEX = SD ;
END //
   DELIMITER;
   
   SELECT * FROM STORE ;
   
   DELIMITER $$
   CREATE PROCEDURE CT (IN VIE TEXT )
   BEGIN
      SELECT * FROM STORE WHERE Category = VIE ;
   END $$
	DELIMITER ;
    
    
    
    

