SELECT NOW(), date_format(NOW() , "%D %M %Y") AS FULL_DAY_DATE;

SELECT NOW() , ADDDATE(NOW() ,  INTERVAL  2 DAY );

SELECT NOW() , ADDDATE(NOW() ,  INTERVAL  2 MONTH );

SELECT NOW() , ADDDATE(NOW() ,  INTERVAL  2 YEAR );

SELECT NOW() , ADDDATE(NOW() ,  INTERVAL  -2 DAY );

SELECT NOW() , DATE_SUB(NOW() ,  INTERVAL - 2 MONTH );

USE SCHOOL;

DELIMITER $$
CREATE PROCEDURE F5(IN E INT , OUT T INT)
BEGIN 
   SELECT SUM(AGE) INTO  T FROM titanic WHERE AGE = E ;
   
   END $$
   DELIMITER ;

SELECT AVG(AGE) FROM titanic;

SELECT * FROM titanic WHERE AGE > (SELECT AVG(AGE) FROM titanic);

-- TRIGER IMP

-- INSERT BEFORE AFTER 
--  UPDATE  BEFORE AFTER
--  DELETE  BEFORE AFTER WORK 










