CREATE DATABASE COMPANY;
USE COMPANY;
CREATE TABLE HR 
(
HR_ID INT PRIMARY KEY ,
HR_NAME TEXT,
HR_DEPARTMENT VARCHAR(50)
);

CREATE TABLE EMP
(
E_ID INT PRIMARY KEY ,
E_FNAME VARCHAR(40) ,
E_AGE INT UNSIGNED ,
E_DEPT VARCHAR(49) ,
E_CITY VARCHAR(70) ,
E_HR INT ,
FOREIGN KEY( E_HR) REFERENCES HR(HR_ID)
); 

SELECT * FROM HR AS H LEFT JOIN EMP AS E ON H.HR_ID = E.E_HR;

SELECT * FROM HR AS H  FULL JOIN EMP AS E ON H.HR_ID = E.E_HR;

CREATE DATABASE SCHOOL;
USE SCHOOL;
CREATE TABLE TEACHER
(
T_ID INT PRIMARY KEY ,
T_FNAME VARCHAR(34) 
);

CREATE TABLE STUDENT 
(
ST_ID INT PRIMARY KEY ,
ST_FNAME VARCHAR(34) ,
ST_MARKS INT ,
ST_T INT,
FOREIGN KEY(ST_T) REFERENCES  TEACHER(T_ID)
);

SELECT 8-9;





