
-- TRIGER IMP

-- INSERT BEFORE AFTER  (NEW) 
--  UPDATE  BEFORE AFTER ( NEW ,OLD)
--  DELETE  BEFORE AFTER(OLD) WORK 

-- STRUCTURE 

DELIMITER //
CREATE TRIGGER DF BEFORE INSERT  ON titanic FOR EACH ROW
BEGIN
 INSERT INTO titanic2 VALUE (NEW.P_ID , ) ;
 END //
 DELIMITER ;